### ISSUE TITLE
Can not Install Library

### ISSUE THREAD

**Issue by fers50** [CESARBR/GT521F52#3]
Hi,

I want to install the Library, but it not working

there some error
pi@raspberrypi:~/GT521F52 $ pip3 install GT_521F52
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting GT_521F52
  Could not find a version that satisfies the requirement GT_521F52 (from versions: )
No matching distribution found for GT_521F52
pi@raspberrypi:~/GT521F52 $ 

can you give me to resolve the error?

**Comment by marlonchalegre** [comment]
Sorry @fers50, the library was not uploaded yet to the pip. This should be solved in a few days

**Comment by marlonchalegre** [comment]
Please try to use pip3 install GT_521F52-Library this should work, for now.

**Comment by marlonchalegre** [comment]
The library was correctly updated and could be installed using pip3 install GT_521F52.

Thanks

**Comment by fers50** [comment]
thank for your attention maybe I wait for the library to the upload,

I want to ask you, their same library with libraryGT_521F52 with a library pip install pyGT511C3
?
